In [2]:
"""generate 100 datapoints for the function f(t)= sin(t) where t is in [0,1]"""
import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd

def f(t):
    return math.sin(10*t)

t = np.linspace(0.0, 1.00, 100)
y = np.zeros(100)
for i in range(100):
    y[i] = f(t[i])

"""store the datapoints in a file called data.csv file"""
data= pd.DataFrame({'t':t, 'y':y})
data.to_csv('data.csv', index=False)
data



t         y
0   0.000000  0.000000
1   0.010101  0.100838
2   0.020202  0.200649
3   0.030303  0.298414
4   0.040404  0.393137
..       ...       ...
95  0.959596 -0.170347
96  0.969697 -0.268843
97  0.979798 -0.364599
98  0.989899 -0.456637
99  1.000000 -0.544021

[100 rows x 2 columns]

In [3]:
"""create a 100* 15 matrix X where each row is a datapoint (t, t^2, t^3, ..., t^15)"""
A= np.ones((100,15))
for i in range(100):
    for j in range(15):
        A[i][j]= t[i]**(j)
A


array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.01010101e-02, 1.02030405e-04, ...,
        1.12817810e-24, 1.13957384e-26, 1.15108468e-28],
       [1.00000000e+00, 2.02020202e-02, 4.08121620e-04, ...,
        4.62101750e-21, 9.33538888e-23, 1.88593715e-24],
       ...,
       [1.00000000e+00, 9.79797980e-01, 9.60004081e-01, ...,
        7.82777756e-01, 7.66964064e-01, 7.51469841e-01],
       [1.00000000e+00, 9.89898990e-01, 9.79900010e-01, ...,
        8.85300222e-01, 8.76357796e-01, 8.67505697e-01],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [4]:
"""create a column vector b that has the values of f(t) for each datapoint"""
b= np.zeros((100,1))
for i in range(100):
    b[i]= f(t[i])
b

array([[ 0.        ],
       [ 0.10083842],
       [ 0.20064886],
       [ 0.2984138 ],
       [ 0.39313661],
       [ 0.48385164],
       [ 0.56963411],
       [ 0.64960951],
       [ 0.72296256],
       [ 0.78894546],
       [ 0.84688556],
       [ 0.8961922 ],
       [ 0.93636273],
       [ 0.96698762],
       [ 0.98775469],
       [ 0.99845223],
       [ 0.99897117],
       [ 0.98930624],
       [ 0.96955595],
       [ 0.93992165],
       [ 0.90070545],
       [ 0.85230712],
       [ 0.79522006],
       [ 0.73002623],
       [ 0.65739025],
       [ 0.57805259],
       [ 0.49282204],
       [ 0.40256749],
       [ 0.30820902],
       [ 0.21070855],
       [ 0.11106004],
       [ 0.01027934],
       [-0.09060615],
       [-0.19056796],
       [-0.28858706],
       [-0.38366419],
       [-0.47483011],
       [-0.56115544],
       [-0.64176014],
       [-0.7158225 ],
       [-0.7825875 ],
       [-0.84137452],
       [-0.89158426],
       [-0.93270486],
       [-0.96431712],
       [-0

In [5]:
"""QR- factorization of A using modified gram schmidt"""
def MGS_qr_factorization(A):
    m,n = A.shape
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    for j in range(n):
        v = A[:,j]
    # for  in range(j):
    #         R[i,j] = Q[:,i].T @ A[:,j]
    #         v = v - R[i,j] * Q[:,i]
    #     R[j,j] = np.linalg.norm(v)
    #     Q[:,j] = v / R[j,j]
    for i in range(n):
        R[i,i] = np.linalg.norm(v)
        Q[:,i] = v / R[i,i]
        for j in range(i+1,n):
            R[i,j] = Q[:,i].T @ A[:,j]
            v = v - R[i,j] * Q[:,i]
    return Q,R

Q,R = MGS_qr_factorization(A)

In [6]:
Q

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.80104381e-29, -5.80104381e-29, -5.80104381e-29, ...,
        -5.80104381e-29, -5.80104381e-29, -5.80104381e-29],
       [ 9.50443018e-25, -9.50443018e-25, -9.50443018e-25, ...,
        -9.50443018e-25, -9.50443018e-25, -9.50443018e-25],
       ...,
       [ 3.78713185e-01, -3.78713185e-01, -3.78713185e-01, ...,
        -3.78713185e-01, -3.78713185e-01, -3.78713185e-01],
       [ 4.37190992e-01, -4.37190992e-01, -4.37190992e-01, ...,
        -4.37190992e-01, -4.37190992e-01, -4.37190992e-01],
       [ 5.03963252e-01, -5.03963252e-01, -5.03963252e-01, ...,
        -5.03963252e-01, -5.03963252e-01, -5.03963252e-01]])

In [7]:
R

array([[  1.98427166,   3.37661545,   3.19361141,   3.03098817,
          2.88552769,   2.75465555,   2.63628768,   2.52871895,
          2.43054075,   2.34057925,   2.25784843,   2.18151397,
          2.11086514,   2.04529276,   1.98427166],
       [  0.        ,  33.77304519,  -3.19361141,  -3.03098817,
         -2.88552769,  -2.75465555,  -2.63628768,  -2.52871895,
         -2.43054075,  -2.34057925,  -2.25784843,  -2.18151397,
         -2.11086514,  -2.04529276,  -1.98427166],
       [  0.        ,   0.        ,  66.15374659,  -3.03098817,
         -2.88552769,  -2.75465555,  -2.63628768,  -2.52871895,
         -2.43054075,  -2.34057925,  -2.25784843,  -2.18151397,
         -2.11086514,  -2.04529276,  -1.98427166],
       [  0.        ,   0.        ,   0.        ,  95.34083658,
         -2.88552769,  -2.75465555,  -2.63628768,  -2.52871895,
         -2.43054075,  -2.34057925,  -2.25784843,  -2.18151397,
         -2.11086514,  -2.04529276,  -1.98427166],
       [  0.        ,   0.  

In [8]:
"""condidtion numbers of Q and R"""
norm_Q=np.linalg.cond(Q,2)
norm_R=np.linalg.cond(R,2)
norm_A=np.linalg.cond(A,2)
print("condition number of Q is", norm_Q)
print("condition number of R is", norm_R)
print("condition number of A is", norm_A)


condition number of Q is 5.466269097975141e+17
condition number of R is 123.53246339346909
condition number of A is 22717771616.09055


In [9]:
"""code for implementing the back substitution"""
def back_substitution(R,b):
    m,n = R.shape
    x=np.zeros(n)
    for i in range(n-1,-1,-1):
        x[i] = (b[i] - R[i,i+1:n] @ x[i+1:n]) / R[i,i]
    return x

In [10]:
"""solve the least squares problem using the QR factorization"""
def least_squares(A,b):
    Q,R = MGS_qr_factorization(A)
    return back_substitution(R, Q.T @ b)



In [11]:
x = least_squares(A,b)
x

array([-0.10156343,  0.0054248 ,  0.00264195,  0.00177667,  0.00136184,
        0.00112159,  0.00096695,  0.00086068,  0.00078452,  0.00072851,
        0.00068681,  0.00065579,  0.00063311,  0.00061725,  0.00060723])

In [25]:
b_=A@x
b.shape

(100, 1)

In [13]:
import numpy as np

def householder_reflection(x):
    """
    Compute the Householder reflection matrix for a given vector x.
    """
    v = x / (x[0] + np.copysign(np.linalg.norm(x), x[0]))
    v[0] = 1
    H = np.eye(x.shape[0])
    H -= (2 / np.dot(v, v)) * np.outer(v, v)
    return H

def householder_qr_factorization(A):
    """
    Compute the QR factorization of a matrix A using Householder reflection.
    """
    m, n = A.shape
    Q = np.eye(m)
    R = A.copy()
    for j in range(n):
        x = R[j:, j]
        H = householder_reflection(x)
        R[j:, j:] = H @ R[j:, j:]
        Q[:, j:] = Q[:, j:] @ H.T
    return Q, R

# Example usage
Q_h, R_h = householder_qr_factorization(A)
print("Q:\n", Q_h)
print("R:\n", R_h)

Q:
 [[-0.1        -0.1714816  -0.21699757 ... -0.04903709 -0.05158455
  -0.08195925]
 [-0.1        -0.16801733 -0.2038462  ...  0.17025447  0.17040656
   0.19164493]
 [-0.1        -0.16455305 -0.19096323 ... -0.19815395 -0.20319649
  -0.17999191]
 ...
 [-0.1         0.16455305 -0.19096323 ...  0.63898578 -0.31316644
   0.02318296]
 [-0.1         0.16801733 -0.2038462  ... -0.31116946  0.62822027
  -0.24818005]
 [-0.1         0.1714816  -0.21699757 ...  0.0361779  -0.22958183
   0.11393141]]
R:
 [[-1.00000000e+01 -5.00000000e+00 -3.35016835e+00 ... -8.12548374e-01
  -7.58236888e-01 -7.11178139e-01]
 [-2.82412982e-15  2.91576465e+00  2.91576465e+00 ...  1.20710257e+00
   1.13884258e+00  1.07835578e+00]
 [-2.82412982e-15 -6.36024067e-17 -7.60299607e-01 ... -1.14426014e+00
  -1.10391243e+00 -1.06562526e+00]
 ...
 [-3.45556916e-15 -1.51012723e-16 -3.23407902e-17 ... -5.90159588e-23
   8.78291994e-24 -2.36640677e-24]
 [-3.50414142e-15 -3.06865691e-18  5.24604566e-17 ... -7.26615437e-24
   1.

In [14]:
"""solve using back substitution"""
"""call the function back_substitution"""
x = back_substitution(R_h, Q_h.T @ b)
x

array([-1.60394949e-07,  1.00000601e+01, -3.14922894e-03, -1.66610619e+02,
       -2.95949305e-01,  8.30456547e+02,  5.52238419e+01, -2.39204387e+03,
        1.80111005e+03, -2.50883034e+03,  1.05301078e+04, -1.68740560e+04,
        1.27872866e+04, -4.80044996e+03,  7.27561013e+02])

In [27]:
import numpy as np

def least_squares_svd(A, b):
    """
    Solve the least squares problem min ||Ax - b||_2 using SVD.
    """
    U, s, Vt = np.linalg.svd(A)
    # d = np.zeros_like(A.T @ b)
    # d[:len(np.diag(s))] = 1 / s
    # x = Vt.T @ np.diag(d) @ U.T @ b
    """convert s to a diagonal matrix and then take the inverse"""
    s=np.diag(s)
    s_inv=np.linalg.inv(s)
    """padding s_inv with zeros"""
    s_inv=np.pad(s_inv, (0, 12), 'constant')
    """U.T @ b"""
    t=(U.T) @ b
    y= s_inv@ t
    x=Vt.T @ y
    return x

# Example usage
x = least_squares_svd(A, b)
print("x:", x)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 100 is different from 27)

In [28]:
U, s, Vt = np.linalg.svd(A)
"""print the shapes of U, s, Vt"""
s=np.diag(s)
s_inv= np.linalg.inv(s)
print(s_inv.shape)
print(U.shape)
print(s.shape)
print(Vt.shape)


(15, 15)
(100, 100)
(15, 15)
(15, 15)


In [26]:
s_inv @ U.T @b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 100 is different from 15)