In [27]:
"""generate 100 datapoints for the function f(t)= sin(t) where t is in [0,1]"""
import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd

def f(t):
    return math.sin(t)

t = np.linspace(0.0, 1.00, 100)
y = np.zeros(100)
for i in range(100):
    y[i] = f(t[i])

"""store the datapoints in a file called data.csv file"""
data= pd.DataFrame({'t':t, 'y':y})
data.to_csv('data.csv', index=False)
data



t         y
0   0.000000  0.000000
1   0.010101  0.010101
2   0.020202  0.020201
3   0.030303  0.030298
4   0.040404  0.040393
..       ...       ...
95  0.959596  0.818960
96  0.969697  0.824714
97  0.979798  0.830385
98  0.989899  0.835971
99  1.000000  0.841471

[100 rows x 2 columns]

In [28]:
"""create a 100* 15 matrix X where each row is a datapoint (t, t^2, t^3, ..., t^15)"""
A= np.ones((100,15))
for i in range(100):
    for j in range(15):
        A[i][j]= t[i]**(j)
A


array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.01010101e-02, 1.02030405e-04, ...,
        1.12817810e-24, 1.13957384e-26, 1.15108468e-28],
       [1.00000000e+00, 2.02020202e-02, 4.08121620e-04, ...,
        4.62101750e-21, 9.33538888e-23, 1.88593715e-24],
       ...,
       [1.00000000e+00, 9.79797980e-01, 9.60004081e-01, ...,
        7.82777756e-01, 7.66964064e-01, 7.51469841e-01],
       [1.00000000e+00, 9.89898990e-01, 9.79900010e-01, ...,
        8.85300222e-01, 8.76357796e-01, 8.67505697e-01],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [29]:
"""create a column vector b that has the values of f(t) for each datapoint"""
b= np.zeros((100,1))
for i in range(100):
    b[i]= f(t[i])
b

array([[0.        ],
       [0.01010084],
       [0.02020065],
       [0.03029839],
       [0.04039305],
       [0.05048358],
       [0.06056897],
       [0.07064817],
       [0.08072016],
       [0.09078392],
       [0.10083842],
       [0.11088263],
       [0.12091552],
       [0.13093608],
       [0.14094328],
       [0.1509361 ],
       [0.16091352],
       [0.17087452],
       [0.18081808],
       [0.1907432 ],
       [0.20064886],
       [0.21053404],
       [0.22039774],
       [0.23023896],
       [0.24005668],
       [0.24984992],
       [0.25961766],
       [0.26935891],
       [0.27907268],
       [0.28875797],
       [0.2984138 ],
       [0.30803919],
       [0.31763315],
       [0.3271947 ],
       [0.33672286],
       [0.34621667],
       [0.35567516],
       [0.36509735],
       [0.3744823 ],
       [0.38382904],
       [0.39313661],
       [0.40240408],
       [0.41163048],
       [0.42081489],
       [0.42995636],
       [0.43905397],
       [0.44810678],
       [0.457

In [30]:
"""QR- factorization of A using modified gram schmidt"""
def MGS_qr_factorizatio(A):
    m,n = A.shape
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    for j in range(n):
        v = A[:,j]
        for i in range(j):
            R[i,j] = Q[:,i].T @ A[:,j]
            v = v - R[i,j] * Q[:,i]
        R[j,j] = np.linalg.norm(v)
        Q[:,j] = v / R[j,j]
    return Q,R

Q,R = MGS_qr_factorization(A)

In [31]:
Q

array([[ 0.1       , -0.1714816 ,  0.21699757, ...,  0.24551698,
         0.24876423,  0.25074947],
       [ 0.1       , -0.16801733,  0.2038462 , ...,  0.02699155,
         0.02688755,  0.02683627],
       [ 0.1       , -0.16455305,  0.19096323, ..., -0.09631527,
        -0.09806116, -0.09912038],
       ...,
       [ 0.1       ,  0.16455305,  0.19096323, ...,  0.12736299,
         0.12463032,  0.12260563],
       [ 0.1       ,  0.16801733,  0.2038462 , ..., -0.0245726 ,
        -0.02525289, -0.02581082],
       [ 0.1       ,  0.1714816 ,  0.21699757, ..., -0.30351747,
        -0.29927832, -0.29621625]])

In [32]:
R

array([[ 1.00000000e+01,  5.00000000e+00,  3.35016835e+00,
         2.52525253e+00,  2.03033670e+00,  1.70042087e+00,
         1.46479075e+00,  1.28808920e+00,  1.15067335e+00,
         1.04075750e+00,  9.50841648e-01,  8.75925784e-01,
         8.12548374e-01,  7.58236888e-01,  7.11178139e-01],
       [ 0.00000000e+00,  2.91576465e+00,  2.91576465e+00,
         2.63296434e+00,  2.35016402e+00,  2.10778436e+00,
         1.90582536e+00,  1.73755023e+00,  1.59622220e+00,
         1.47632936e+00,  1.37358466e+00,  1.28469039e+00,
         1.20710257e+00,  1.13884258e+00,  1.07835578e+00],
       [ 0.00000000e+00,  0.00000000e+00,  7.60299607e-01,
         1.14044941e+00,  1.30660669e+00,  1.36576770e+00,
         1.37116960e+00,  1.34943097e+00,  1.31429603e+00,
         1.27307186e+00,  1.22971856e+00,  1.18639443e+00,
         1.14426014e+00,  1.10391243e+00,  1.06562526e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.94630675e-01,  3.89261349e-01,  5.41699869

In [37]:
"""code for implementing the back substitution"""
def back_substitution(R,b):
    m,n = R.shape
    x=np.zeros(n)
    for i in range(n-1,-1,-1):
        x[i] = (b[i] - R[i,i+1:n] @ x[i+1:n]) / R[i,i]
    return x

In [38]:
"""solve the least squares problem using the QR factorization"""
def least_squares(A,b):
    Q,R = MGS_qr_factorization(A)
    return back_substitution(R, Q.T @ b)



In [41]:
x = least_squares(A,b)
x

array([ 6.63738398e-11,  9.99999993e-01,  1.54392092e-07, -1.66668113e-01,
        7.14046166e-06,  8.31268562e-03,  3.66504601e-05, -2.38678553e-04,
        2.65499889e-05, -6.82617951e-06,  1.47183187e-06, -3.95467548e-08,
       -3.52125928e-09, -5.37429552e-10, -9.16062152e-11])

In [40]:
b_=A@x
np.linalg.norm(b-b_)

35.36567756961767

In [45]:
import numpy as np

def householder_reflection(x):
    """
    Compute the Householder reflection matrix for a given vector x.
    """
    v = x / (x[0] + np.copysign(np.linalg.norm(x), x[0]))
    v[0] = 1
    H = np.eye(x.shape[0])
    H -= (2 / np.dot(v, v)) * np.outer(v, v)
    return H

def qr_factorization(A):
    """
    Compute the QR factorization of a matrix A using Householder reflection.
    """
    m, n = A.shape
    Q = np.eye(m)
    R = A.copy()
    for j in range(n):
        x = R[j:, j]
        H = householder_reflection(x)
        R[j:, j:] = H @ R[j:, j:]
        Q[:, j:] = Q[:, j:] @ H.T
    return Q, R

# Example usage
Q_h, R_h = qr_factorization(A)
print("Q:\n", Q_h)
print("R:\n", R_h)

Q:
 [[-0.1        -0.1714816  -0.21699757 ... -0.04903709 -0.05158455
  -0.08195925]
 [-0.1        -0.16801733 -0.2038462  ...  0.17025447  0.17040656
   0.19164493]
 [-0.1        -0.16455305 -0.19096323 ... -0.19815395 -0.20319649
  -0.17999191]
 ...
 [-0.1         0.16455305 -0.19096323 ...  0.63898578 -0.31316644
   0.02318296]
 [-0.1         0.16801733 -0.2038462  ... -0.31116946  0.62822027
  -0.24818005]
 [-0.1         0.1714816  -0.21699757 ...  0.0361779  -0.22958183
   0.11393141]]
R:
 [[-1.00000000e+01 -5.00000000e+00 -3.35016835e+00 ... -8.12548374e-01
  -7.58236888e-01 -7.11178139e-01]
 [-2.82412982e-15  2.91576465e+00  2.91576465e+00 ...  1.20710257e+00
   1.13884258e+00  1.07835578e+00]
 [-2.82412982e-15 -6.36024067e-17 -7.60299607e-01 ... -1.14426014e+00
  -1.10391243e+00 -1.06562526e+00]
 ...
 [-3.45556916e-15 -1.51012723e-16 -3.23407902e-17 ... -5.90159588e-23
   8.78291994e-24 -2.36640677e-24]
 [-3.50414142e-15 -3.06865691e-18  5.24604566e-17 ... -7.26615437e-24
   1.

In [47]:
"""solve using back substitution"""
"""call the function back_substitution"""
x = back_substitution(R_h, Q_h.T @ b)
x

array([ 5.32907052e-16,  1.00000000e+00,  3.93612451e-12, -1.66666667e-01,
        7.79976124e-10,  8.33332843e-03,  2.01587564e-08, -1.98469215e-04,
        1.10480307e-07,  2.60412403e-06,  1.44834207e-07, -1.18804424e-07,
        3.88582488e-08, -9.01377615e-09,  9.14303062e-10])

In [50]:
import numpy as np

def least_squares_svd(A, b):
    """
    Solve the least squares problem min ||Ax - b||_2 using SVD.
    """
    U, s, Vt = np.linalg.svd(A)
    d = np.zeros_like(A.T @ b)
    d[:len(s)] = 1 / s
    x = Vt.T @ np.diag(d) @ U.T @ b
    return x

# Example usage
x = least_squares_svd(A, b)
print("x:", x)

ValueError: could not broadcast input array from shape (15,) into shape (15,1)

In [51]:
s.shape

NameError: name 's' is not defined