# Page Rank Algorithm using Power iteration method

In [2]:
"""page rank algorithm"""
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import networkx as nx


# 
\begin{table}[H]
    \centering
    \begin{tabular}{lccc}
     \toprule \\
     \textbf{Node} & \textbf{Outgoing Neighbors} & \textbf{Count} & \textbf{probability}\\
        \midrule \\

        0 & {8, 1}& 2 & 0.5\\
        1 &{2, 7} & 2& 0.5\\
        2 & {0}& 1& 1\\
        3& {1}& 1& 1\\
        4& {5, 7}& 2& 0.5\\
        5&{6, 9}& 2& 0.5\\
        6& {2, 8}& 2& 0.5\\
        7&{5, 8}& 2& 0.5\\
        8&{1, 9}&2 & 0.5\\
        9&{7}& 1& 1\\
        
        \bottomrule
    \end{tabular}
    \caption{Edge Weights Evaluation of the graph}
    \label{tab:my_label}
\end{table}

In [3]:
""" convert into a network with egdes, edge-weights and nodes from the above matrix"""
def convert_to_network(matrix):
    G = nx.DiGraph()
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if matrix[i][j] != 0:
                G.add_edge(i, j, weight = matrix[i][j])
    return G

"""calculate the page rank of the network"""
def page_rank(G):
    return nx.pagerank(G)



In [4]:
"""initialize a 10 by 10 matrix with all zeros"""
transition_matrix = np.zeros((10, 10))
transition_matrix[0][1] = 0.5
transition_matrix[0][8] = 0.5
transition_matrix[1][2] = 0.5
transition_matrix[1][7] = 0.5
transition_matrix[2][0] = 1.0
transition_matrix[3][1] = 1.0
transition_matrix[4][5] = 0.5
transition_matrix[4][7] = 0.5
transition_matrix[5][6] = 0.5
transition_matrix[5][9] = 0.5
transition_matrix[6][2] = 0.5
transition_matrix[6][8] = 0.5
transition_matrix[7][5] = 0.5
transition_matrix[7][8] = 0.5
transition_matrix[8][1] = 0.5
transition_matrix[8][9] = 0.5
transition_matrix[9][7] = 1.0
transition_matrix

array([[0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0. ],
       [0. , 0. , 0.5, 0. , 0. , 0. , 0. , 0.5, 0. , 0. ],
       [1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0.5, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0. , 0.5],
       [0. , 0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0.5, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. ]])

# In-built page rank algorithm

In [5]:
G=convert_to_network(transition_matrix)
print("Page rank of the network is: ", page_rank(G))

Page rank of the network is:  {0: 0.09863627405577377, 1: 0.13823979964883046, 8: 0.16133742593203582, 2: 0.09839626652322582, 7: 0.18769899564477366, 3: 0.015000000000000003, 4: 0.015000000000000003, 5: 0.10114665831752459, 6: 0.05798792455806254, 9: 0.1265566553197736}


In [6]:
""" initializing the reference page rank vector"""
reference_page_rank_vector = np.zeros(10, dtype = float)
for i in range(10):
    reference_page_rank_vector[i] = page_rank(G)[i]
reference_page_rank_vector

array([0.09863627, 0.1382398 , 0.09839627, 0.015     , 0.015     ,
       0.10114666, 0.05798792, 0.187699  , 0.16133743, 0.12655666])

## (a)
#### Plot of the 2-norm of the residual of eigenvalue problem involving the dominant
#### eigenvector with iteration number. (Use the unit vector generated at the end of
#### each iteration in your power iteration algorithm to compute the eigenvalue problem
#### residual at each iteration)


## (b)
#### Plot of the 2-norm of the difference between the vectors corresponding to the
#### successive iterates of your power iteration with number of iterations.

## (c) 
#### Compute the Rayleigh quotient at each iteration of your algorithm and plot the
#### convergence with respect to iteration number.

## (d)
#### State the node numbers with least and highest page ranks.

In [8]:
"""Generate 10 random vectors each of length 10 with entries between 0 and 1 and normalize them"""
random_vectors = np.random.rand(10, 10)
for i in range(10):
    random_vectors[i] = random_vectors[i]/np.linalg.norm(random_vectors[i])

for i in range(10):
    print("Random vector ", i, " is: ", random_vectors[i])


Random vector  0  is:  [0.16374649 0.49489776 0.2771365  0.47202545 0.35398527 0.33423208
 0.05036567 0.01674007 0.43277677 0.03900393]
Random vector  1  is:  [0.20078251 0.42828634 0.47287851 0.21416344 0.05125201 0.36399513
 0.49679623 0.10277505 0.33802694 0.00514724]
Random vector  2  is:  [0.57716164 0.030206   0.1028643  0.1322496  0.1302072  0.46959716
 0.33121089 0.34169155 0.40260775 0.1089901 ]
Random vector  3  is:  [0.3065128  0.23292454 0.46586838 0.02436988 0.07779845 0.31846849
 0.08859399 0.33022318 0.48838962 0.41385188]
Random vector  4  is:  [0.40792883 0.31732089 0.17852802 0.41165436 0.3862456  0.07330235
 0.33162438 0.49656368 0.10262179 0.09964741]
Random vector  5  is:  [0.08397177 0.47541102 0.08239731 0.50164183 0.23355545 0.34250409
 0.09952265 0.44246658 0.31766453 0.17334898]
Random vector  6  is:  [0.45614207 0.34046336 0.24632604 0.05315536 0.08389827 0.37545158
 0.41421807 0.3099558  0.33065005 0.29586421]
Random vector  7  is:  [0.05532005 0.15233556 0.

In [15]:
"""exchange the maximum element of the random vector with its 8th element"""
for i in range(10):
    max_element = np.argmax(random_vectors[i])
    random_vectors[i][max_element], random_vectors[i][7] = random_vectors[i][7], random_vectors[i][max_element]
    print("Random vector ", i, " after exchange is: ", random_vectors[i])


Random vector  0  after exchange is:  [0.16374649 0.01674007 0.2771365  0.47202545 0.35398527 0.33423208
 0.05036567 0.49489776 0.43277677 0.03900393]
Random vector  1  after exchange is:  [0.20078251 0.42828634 0.47287851 0.21416344 0.05125201 0.36399513
 0.10277505 0.49679623 0.33802694 0.00514724]
Random vector  2  after exchange is:  [0.34169155 0.030206   0.1028643  0.1322496  0.1302072  0.46959716
 0.33121089 0.57716164 0.40260775 0.1089901 ]
Random vector  3  after exchange is:  [0.3065128  0.23292454 0.46586838 0.02436988 0.07779845 0.31846849
 0.08859399 0.48838962 0.33022318 0.41385188]
Random vector  4  after exchange is:  [0.40792883 0.31732089 0.17852802 0.41165436 0.3862456  0.07330235
 0.33162438 0.49656368 0.10262179 0.09964741]
Random vector  5  after exchange is:  [0.08397177 0.47541102 0.08239731 0.44246658 0.23355545 0.34250409
 0.09952265 0.50164183 0.31766453 0.17334898]
Random vector  6  after exchange is:  [0.3099558  0.34046336 0.24632604 0.05315536 0.08389827 

In [17]:
"""power iteration method of finding the page rank"""
def power_iteration_method(matrix, reference_vector,init_vector, tolerance= 1e-3, MAX_ITER=100000):
    """initialize the page rank vector"""
    page_rank_vector=init_vector
    residual_two_norm_ref=dict()
    residua_two_norm_iter=dict()
    residual_eigen_vector_two_norm_ref=dict()
    """calculate the page rank vector until the tolerance is reached"""
    iter = 0
    while iter < MAX_ITER:
        iter+=1
        new_page_rank_vector = np.dot(matrix, page_rank_vector)
        new_page_rank_vector = new_page_rank_vector / np.linalg.norm(new_page_rank_vector, 2)
        residual_two_norm_ref[np.linalg.norm(new_page_rank_vector - reference_vector, 2)]= iter
        residual_eigen_vector_two_norm_ref[np.linalg.norm(new_page_rank_vector-page_rank_vector)]= iter
        residua_two_norm_iter[np.linalg.norm(new_page_rank_vector - page_rank_vector, 2)]= iter
        if np.linalg.norm(new_page_rank_vector - reference_vector, 2) < tolerance:
            break
    page_rank_vector = new_page_rank_vector
    return page_rank_vector, residual_eigen_vector_two_norm_ref, residual_two_norm_ref, residua_two_norm_iter

page_rank_vector, x_plot_a, x_plot_b, x_plot_c = power_iteration_method(transition_matrix, reference_page_rank_vector, 10000)
"""call the power iteration method for all the random vectors"""
for i in range(10):
    print("Page rank vector for random vector ", i, " is: ", power_iteration_method(transition_matrix, reference_page_rank_vector, random_vectors[i])[0])
    print("error with respect to the reference page rank vector is: ", power_iteration_method(transition_matrix, reference_page_rank_vector, random_vectors[i])[1])

# """calculate the page rank using power iteration method"""
# power_iteration_method(transition_matrix, reference_page_rank_vector)

# """calculate the page rank using power iteration method for different values of alpha"""
# alpha = np.linspace(0, 1, 10)
# page_rank_vector = []
# for i in alpha:
#     page_rank_vector.append(power_iteration_method(transition_matrix, i, 100))
#     """calculate the error with respect to the reference page rank vector"""
#     error = np.linalg.norm(page_rank_vector - reference_page_rank_vector)
#     print("Error for alpha = ", i, " is: ", error)
# page_rank_vector = np.array(page_rank_vector)
# page_rank_vector



Page rank vector for random vector  0  is:  [0.23442242 0.40261482 0.17078715 0.01745985 0.43239009 0.04660613
 0.3702188  0.39999407 0.02907042 0.51617702]
error with respect to the reference page rank vector is:  {0.9811708246817272: 100000}
Page rank vector for random vector  1  is:  [0.3267399  0.41344895 0.1712189  0.36522461 0.36702336 0.0460158
 0.34575306 0.29932747 0.18480698 0.42364696]
error with respect to the reference page rank vector is:  {0.792070958916472: 100000}
Page rank vector for random vector  2  is:  [0.1980061  0.31110213 0.31263799 0.02763763 0.47887717 0.20138565
 0.23124623 0.39902126 0.06368023 0.52808638]
error with respect to the reference page rank vector is:  {0.8247699416688271: 100000}
Page rank vector for random vector  3  is:  [0.24812817 0.42045503 0.27010484 0.20525748 0.35550926 0.22138237
 0.35076541 0.28581964 0.28497576 0.4303781 ]
error with respect to the reference page rank vector is:  {0.5552099099190956: 100000}
Page rank vector for rando

In [57]:
"""power iteration method of finding the page rank"""
def power_iteration_method(matrix, reference_vector,MAX_ITER,tolerance= 1e-3):
    """initialize the page rank vector"""
    page_rank_vector=np.ones(len(matrix))/ np.linalg.norm(np.ones(len(matrix)), 2)
    residual_two_norm_ref=dict()
    residua_two_norm_iter=dict()
    residual_eigen_vector_two_norm_ref=dict()
    """calculate the page rank vector until the tolerance is reached"""
    iter = 0
    while iter<MAX_ITER:
        iter+=1
        new_page_rank_vector = np.dot(matrix, page_rank_vector)
        new_page_rank_vector = new_page_rank_vector / np.linalg.norm(new_page_rank_vector, 2)
        residual_two_norm_ref[np.linalg.norm(new_page_rank_vector - reference_vector, 2)]= iter
        residual_eigen_vector_two_norm_ref[np.linalg.norm(new_page_rank_vector-page_rank_vector)]= iter
        residua_two_norm_iter[np.linalg.norm(new_page_rank_vector - page_rank_vector, 2)]= iter
        if np.linalg.norm(new_page_rank_vector - reference_vector, 2) < tolerance:
            break
    page_rank_vector = new_page_rank_vector
    return page_rank_vector, residual_eigen_vector_two_norm_ref, residual_two_norm_ref, residua_two_norm_iter

page_rank_vector, x_plot_a, x_plot_b, x_plot_c = power_iteration_method(transition_matrix, reference_page_rank_vector, 10000)

In [58]:
page_rank_vector

array([0.31622777, 0.31622777, 0.31622777, 0.31622777, 0.31622777,
       0.31622777, 0.31622777, 0.31622777, 0.31622777, 0.31622777])